---

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart ssh
  service: name=ssh state=restarted

- name: restart postgres
  service: name=postgresql state=restarted
  become: true

- name: reload pg config
  command: psql postgres -c 'SELECT pg_reload_conf();'

- name: restart postfix
  service: name=postfix state=restarted

- name: restart opendmarc
  service: name=opendmarc state=restarted
